epoch_size: 50
warm_start: 0
warm_start_epoch_number: 20
train_mode: 1
allow_wrong_service: 1
max_turn: 8
simulate_epoch_number: 1000
evaluate_epoch_number: 200
save_performance: False
# 0: rule 1: dqn 2: AC
agent_id: 1
is_relational_dqn: False
dqn_type: DuelingDQN
batch_size: 30
prioritized_replay: True
#saved_model: model/dqn/checkpoint/change_goalset_s0.83.pkl
saved_model: model/dqn/checkpoint/without_maxslot_model_d_agent_dqn_s0.96_r77.925_t5.0_wd0.015_e440.pkl
#input_size_dqn: 1222
hidden_size_dqn: 300
experience_replay_pool_size: 20000
epsilon: 0.1
gamma: 1.0
dqn_learning_rate: 0.001
performance_save_path: model/dqn/learning_rate
