epoch_size: 50
warm_start: 1
warm_start_epoch_number: 20
train_mode: 0
allow_wrong_service: 1
max_turn: 8
#saved_model: model/model_d_agent_dqn_s1.0_r36.4_t3.36_wd0.0_e49.pkl
DQN:
  saved_model: model/model_d_agent_dqn_s1.0_r72.2_t5.64_wd0.0_e359.pkl
  input_size_dqn: 1121
  hidden_size_dqn: 300
  experience_replay_pool_size: 20000
  epsilon: 0.1
  gamma: 1.0
  dqn_learning_rate: 0.001
  save_performance: 0
  performance_save_path: /home/yanking/disk1/nizepu/govChatbot/model/dqn/learning_rate
AC:
  OUTPUT_GRAPH: False
  MAX_EPISODE: 500
  DISPLAY_REWARD_THRESHOLD: 200  # renders environment if total episode reward is greater then this threshold
  MAX_EP_STEPS: 1000  # maximum time step in one episode
  RENDER: False  # rendering wastes time
  GAMMA: 0.9  # reward discount in TD error
  LR_A: 0.001  # learning rate for actor
  LR_C: 0.01  # learning rate for critic
  ITER_NUMS: 500
  LOG_INTERVAL: 10