epoch_size: 50
warm_start: 0
warm_start_epoch_number: 20
train_mode: 1
allow_wrong_service: 0
max_turn: 8
simulate_epoch_number: 500
evaluate_epoch_number: 200
save_performance: True
# 0: rule 1: dqn 2: AC
agent_id: 1
is_relational_dqn: False
dqn_type: DuelingDQN
batch_size: 30
prioritized_replay: True
saved_model: model/dqn/checkpoint/model_d_agent_dqn_s1.0_r69.2_t5.52_wd0.0_e173.pkl
input_size_dqn: 1221
hidden_size_dqn: 300
experience_replay_pool_size: 20000
epsilon: 0.1
gamma: 1.0
dqn_learning_rate: 0.001
performance_save_path: model/dqn/learning_rate
